name: 24/7 Bot Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # fallback: runs every hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python (or Node.js, depending on your bot)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot (with timeout)
        run: |
          echo "Bot started..."
          timeout 3540 python3 bot.py  # 59 minutes
          echo "Bot ended. Restarting..."

      - name: Trigger next run
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/bot.yml/dispatches \
            -d '{"ref":"main"}'
